
#define MENU_TARE "Tare"
#define MENU_CALIBRATION "Calibration"
#define MENU_CORRECTION "Correction"
#define MENU_JARTYPES "Jar types"
#define MENU_AUTO "Automatic"
#define MENU_SERVO "Servo"
#define MENU_PARAMETERS "Parameters"
#define MENU_COUNT "Count"
#define MENU_COUNTTRIP "Trip count"
#define MENU_RESETPREFS "Reset Prefs"
//#define MENU_ ""

#define JARTYPE_1 "TO42"
#define JARTYPE_2 "TO63"
#define JARTYPE_3 "TO82"

#define DIALOGUE_RESET "Reset"
#define DIALOGUE_CANCEL "Cancel"
#define DIALOGUE_OK "OK"
#define DIALOGUE_MISSING "Missing"
#define DIALOGUE_SCALECAL1 "Please empty"
#define DIALOGUE_SCALECAL2 "the scale"
#define DIALOGUE_SCALECAL3 "and confirm"
#define DIALOGUE_SCALECAL4 "with OK"
#define DIALOGUE_SCALECAL5 "Pls. put "
#define DIALOGUE_SCALECAL6 "on the scale"
#define DIALOGUE_CORRECTION "Correction"
#define DIALOGUE_FORMER "former value"
#define SERVO_MINIMUM "Minimum   %3d"
#define SERVO_MAXIMUM "Maximum   %3d"
#define DIALOGUE_SAVE "Save"
#define SERVO_FINE "Finedos.  %3d"
#define SERVO_LIVESETUP "Livesetup %3s"
#define DIALOGUE_OFF "OFF"
#define DIALOGUE_ON "ON"
#define SERVO_PREVIOUS "previous: %3d"

#define AUTOMATIC_AUTOSTART "Autostart %3s"
#define AUTOMATIC_JARTOLERANCE "Jar tol. %c%2dg"
#define AUTOMATIC_AUTOCORRECTION "Autocorr. %3s"
#define AUTOMATIC_OVERFILL "Overfill %2dg"

#define PARAMETER_BUZZER "Buzzer    %3s"
#define PARAMETER_MENU "Menu   %6s"
#define PARAMETER_LIST " List"
#define PARAMETER_SCROLL "Scroll"

#define CLEARPREFS_ERASE "Erase EEPROM"
#define DIALOGUE_START "START"

#define SCREEN_NOJAR1 "Put a jar"
#define SCREEN_NOJAR2 "on scale"
#define SCREEN_NOTARE "no tare!"
#define SCREEN_SHORT1 "A=%-3d %2s %3d%%"
#define SCREEN_SHORT2 "AS"
#define SCREEN_SHORT3 "a"
#define SCREEN_SHORT4A "c=   %s %3s-%3s"
#define SCREEN_SHORT4B "c=   %s %3d-%3s"
#define SCREEN_SHORT4C "c=%-3d"
#define SCREEN_SHORT4D "c=%-3d%s %3s-%3s"
#define SCREEN_SHORT4E "c=%-3d%s %3d-%3s"





#define SCREEN_SHORT5 "Manual  %s"
#define SCREEN_SHORT6 "Tare"
#define SCREEN_SHORT7 "A=%-3d    %3d%%"

#define STARTUP_NOTCAL1 "Scale not"
#define STARTUP_NOTCAL2 "calibrated"
#define STARTUP_NOSCALE1 "No scale"
#define STARTUP_NOSCALE2 "detected"
#define STARTUP_WEIGHTON1 "Pls. empty"
#define STARTUP_WEIGHTON2 "the scale"

#define COUNT_DISPLAY1 "%4dg %3s"
#define COUNT_DISPLAY2 "%5d Pcs."
#define COUNT_DISPLAY3 "Total trip:"
#define COUNT_DISPLAY4 "Total:"